### ISSUE TITLE
Add build.vc to distributed tarball

### ISSUE THREAD

**Issue by isuruf** [wbhart/mpir#211] opened 2017-02-21 15:28 UTC
The tarball doesn't seem to contain "build.vc" which is referred to in Visual Studio build files in other folders like "build.vc14"
Here's an error when trying to compile from the tarball

C:\bld\mpir_1487688618634\work\mpir-3.0.0\build.vc14\lib_mpir_gc\lib_mpir_gc.vcxproj(58,5): error MSB4019: The imported project "C:\bld\mpir_1487688618634\work\mpir-3.0.0\build.vc\mpir_release_lib.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

**Comment by wbhart** [comment] 2017-02-21 15:56
Probably the entire directory needs to be added to the tarball. Thanks. I will try to fix this.

**Comment by wbhart** [comment] 2017-02-21 15:56
Obviously the issue is make dist doesn't know about the new directory Brian added.

**Comment by wbhart** [comment] 2017-02-21 16:18
Actually, it seems someone already added build.vc15 to Makefile.am, but build.vc is missing. I'll add it now.

**Comment by isuruf** [comment] 2017-02-21 16:19
Thanks.

**Comment by wbhart** [comment] 2017-02-21 16:29
I believe this is fixed in rc2.

**Closed by wbhart** 2017-02-21 16:29 UTC

**Comment by isuruf** [comment] 2017-02-21 16:40
Works for me. Thanks
