### ISSUE TITLE
build.vc15 - msbuild.bat cant find path to Professional and Enterprise VS 2017 

### ISSUE THREAD

**Issue by mmcs85** [wbhart/mpir#226] opened 2017-10-19 15:28 UTC
Hi, this line only finds the community version of VS 2017, maybe check if path exists and check if Professional and Enterprise Paths also exists.

https://github.com/wbhart/mpir/blob/28c220067a07b110dd3ae6e409612df2fb8623d0/build.vc15/msbuild.bat#L24

Regards

**Comment by madscientist** [comment] 2018-02-10 14:25
I have the same problem.  I really think this mode of trying to keep up with the various releases and hardcode them is going to cause lots of angst.  What I've done in the past is twofold: first, I check to see if the current environment is already set up for Visual Studio.  If it is, then the user has already run vcvarsall.bat or similar and I don't need to provide a fully-qualified path when I invoke msbuild.exe.  It's already set up for me.  Maybe they're running the script from within a Visual Studio shell or something.  If the Visual Studio environment is not set up, then I look for it either by searching for "all the places" starting with the newest Visual Studio I know about, or by starting with some version the user requested.  If I find it, I run vcvarsall.bat from that release.  Then again, I don't need fully-qualified paths for msbuild.

Starting with Visual Studio 17 this gets simpler (or at least, it will be simpler going forward) because they've introduced the "vswhere.exe" which is always installed at the same place, and will print out the path to Visual Studio for you.  Of course, until VS 17 is ubiquitous, vswhere is just one more thing you have to check for to be portable *sigh*.

**Comment by BrianGladman** [comment] 2018-02-23 17:38
Fixed in my repository for the new Windows build files in mpir\msvc

**Comment by KevinHake** [comment] 2018-08-25 20:48
@BrianGladman - is this separate from Issue #229, or the same thing/same code change?

**Comment by BrianGladman** [comment] 2018-08-25 22:44
@KevinHake  - Sadly it is a new (albeit related) issue caused by changes in the location of some Microsoft build tools.    I have now fixed it in my repository at: https://github.com/BrianGladman/mpir

**Comment by wbhart** [comment] 2018-09-28 21:51
I assume this support request was resolved.

**Closed by wbhart** 2018-09-28 21:51 UTC
